version: "3"

services:
  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - "80:80"

  flask1:
    build: ./flask
    container_name: flask1
    ports:
      - "5000:80"
    environment:
      - 'GL_DB=gldb'
      - 'RUN=flask run --host=0.0.0.0'
      - 'GL_APP=./src/main.py'
    links:
      - 'gldb:database'

  flask2:
    build: ./flask
    container_name: flask2
    ports:
      - "5001:80"
    environment:
      - 'GL_DB=gldb'
      - 'RUN=flask run --host=0.0.0.0'
      - 'GL_APP=./src/main.py'
    links:
      - 'gldb:database'

  gldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "DATABASE"
      MYSQL_USER: "USER"
      MYSQL_PASSWORD: "PASSWORD"
      MYSQL_ROOT_PASSWORD: "PASSWORD"
    volumes:
      - gl-db:/var/lib/mysql

volumes:
  gl-db:
